version: '3.7'
services:
  database:
    image: mysql:5.7
    volumes: 
      - ./docker-data:/docker-entrypoint-initdb.d
    networks: 
      - db
    environment: 
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=prooph"
  app:
    image: jguyomard/laravel-php:7.3
    volumes: 
      - ./:/var/www
    networks: 
      - db
    user: $UID:$GID

networks: 
  db:    